name: chlu
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2024.3.11
  - expat=2.6.2
  - libffi=3.4.4
  - openssl=3.0.14
  - pip=24.0
  - python=3.12.4
  - sqlite=3.45.3
  - tk=8.6.14
  - vc=14.2
  - vs2015_runtime=14.29.30133
  - wheel=0.43.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - anyio==4.4.0
      - apscheduler==3.10.4
      - astroid==3.2.2
      - black==24.4.2
      - brotli==1.1.0
      - certifi==2024.7.4
      - charset-normalizer==3.3.2
      - click==8.1.7
      - colorama==0.4.6
      - dill==0.3.8
      - h11==0.14.0
      - httpcore==1.0.5
      - httpx==0.27.0
      - idna==3.7
      - isort==5.13.2
      - mccabe==0.7.0
      - mutagen==1.47.0
      - mypy-extensions==1.0.0
      - packaging==24.1
      - pathspec==0.12.1
      - platformdirs==4.2.2
      - pycryptodomex==3.20.0
      - pylint==3.2.3
      - python-dotenv==1.0.1
      - python-telegram-bot==21.3
      - pytz==2024.1
      - requests==2.32.3
      - setuptools==72.1.0
      - six==1.16.0
      - sniffio==1.3.1
      - tomlkit==0.12.5
      - tzdata==2024.1
      - tzlocal==5.2
      - urllib3==2.2.2
      - websockets==12.0
      - yt-dlp==2024.8.1
