# -*- coding: utf-8 -*-
"""
Cookie 格式转换工具
将 EditThisCookie (JSON) 或其他格式转换为 Netscape Cookie 格式（yt-dlp 兼容）

支持的输入格式：
1. EditThisCookie JSON 格式
2. Chrome DevTools JSON 格式

使用方法：
    python scripts/convert_cookies.py input.json output.txt
"""

import sys
import json
from datetime import datetime


def json_to_netscape(json_cookies):
    """
    将 JSON 格式的 cookies 转换为 Netscape 格式
    
    Args:
        json_cookies: JSON 格式的 cookies 列表
    
    Returns:
        Netscape 格式的字符串
    """
    lines = [
        "# Netscape HTTP Cookie File",
        "# This file is generated by cookie converter. Do not edit manually.",
        ""
    ]
    
    for cookie in json_cookies:
        # 提取字段（兼容不同的 JSON 格式）
        domain = cookie.get('domain', cookie.get('Domain', ''))
        flag = "TRUE" if domain.startswith('.') else "FALSE"
        path = cookie.get('path', cookie.get('Path', '/'))
        secure = "TRUE" if cookie.get('secure', cookie.get('Secure', False)) else "FALSE"
        
        # 过期时间处理
        expiration = cookie.get('expirationDate', cookie.get('Expires', 0))
        if isinstance(expiration, float):
            expiration = int(expiration)
        elif isinstance(expiration, str):
            try:
                # 尝试解析日期字符串
                dt = datetime.strptime(expiration, "%Y-%m-%dT%H:%M:%S.%fZ")
                expiration = int(dt.timestamp())
            except:
                expiration = 0
        
        name = cookie.get('name', cookie.get('Name', ''))
        value = cookie.get('value', cookie.get('Value', ''))
        
        if not name:
            continue
        
        # Netscape 格式：domain flag path secure expiration name value
        line = f"{domain}\t{flag}\t{path}\t{secure}\t{expiration}\t{name}\t{value}"
        lines.append(line)
    
    return '\n'.join(lines)


def convert_file(input_file, output_file):
    """
    转换 cookie 文件
    
    Args:
        input_file: 输入文件路径（JSON 格式）
        output_file: 输出文件路径（Netscape 格式）
    """
    print(f"读取输入文件: {input_file}")
    
    try:
        with open(input_file, 'r', encoding='utf-8') as f:
            content = f.read().strip()
            
        # 尝试解析 JSON
        try:
            cookies = json.loads(content)
        except json.JSONDecodeError as e:
            print(f"❌ JSON 解析失败: {e}")
            print("\n输入文件应该是有效的 JSON 格式")
            print("如果使用 EditThisCookie，请选择 'Export' 导出为 JSON 格式")
            return False
        
        # 确保是列表
        if not isinstance(cookies, list):
            print("❌ JSON 内容不是数组格式")
            print("请确保导出的是完整的 cookies 数组")
            return False
        
        print(f"✅ 成功读取 {len(cookies)} 条 cookies")
        
        # 转换为 Netscape 格式
        print("正在转换格式...")
        netscape_content = json_to_netscape(cookies)
        
        # 写入输出文件
        print(f"写入输出文件: {output_file}")
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write(netscape_content)
        
        print(f"✅ 转换完成！")
        print(f"\n输出文件: {output_file}")
        print(f"总计: {len(cookies)} 条 cookies")
        
        return True
        
    except FileNotFoundError:
        print(f"❌ 文件不存在: {input_file}")
        return False
    except Exception as e:
        print(f"❌ 转换失败: {e}")
        import traceback
        traceback.print_exc()
        return False


def show_help():
    """显示帮助信息"""
    print("=" * 70)
    print("Cookie 格式转换工具")
    print("将 EditThisCookie (JSON) 转换为 Netscape Cookie 格式（yt-dlp 兼容）")
    print("=" * 70)
    print()
    print("使用方法:")
    print("  python scripts/convert_cookies.py <输入文件.json> <输出文件.txt>")
    print()
    print("示例:")
    print("  python scripts/convert_cookies.py youtube_cookies.json config/youtube.cookies")
    print()
    print("步骤:")
    print("  1. 在 Chrome 中访问 youtube.com 并登录")
    print("  2. 使用 EditThisCookie 扩展导出 cookies (JSON 格式)")
    print("  3. 保存为 youtube_cookies.json")
    print("  4. 运行此脚本进行转换")
    print("  5. 转换后的文件可直接用于 yt-dlp")
    print()


def main():
    """主函数"""
    if len(sys.argv) < 3:
        show_help()
        return 1
    
    input_file = sys.argv[1]
    output_file = sys.argv[2]
    
    print()
    success = convert_file(input_file, output_file)
    print()
    
    return 0 if success else 1


if __name__ == "__main__":
    sys.exit(main())



